Work around a C++ standard defect
Reported on Solaris 5.9:
nmap_dns.cc:1320: error: no match for 'operator!=' in 'c !=
std::basic_string<_CharT, _Traits, _Alloc>::rend() [with _CharT = char,
_Traits = std::char_traits<char>, _Alloc = std::allocator<char>]()'

Reference:
https://stackoverflow.com/questions/2135094/gcc-reverse-iterator-comparison-operators-missing