Cherry-pick changes to require <linux/compiler.h>.
I needed this to build with --with-libpcap=included on Linux 2.6.16,
otherwise I got this error:

gcc -g -O2 -O2 -fpic -I.  -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -c ./pcap-usb-linux.c
./pcap-usb-linux.c: In function ‘probe_devices’:
./pcap-usb-linux.c:234: error: storage size of ‘ctrl’ isn’t known
./pcap-usb-linux.c:279: error: ‘USBDEVFS_CONTROL’ undeclared (first use in this function)
./pcap-usb-linux.c:279: error: (Each undeclared identifier is reported only once
./pcap-usb-linux.c:279: error: for each function it appears in.)
make[1]: *** [pcap-usb-linux.o] Error 1

commit a092bafeee07c97352d2c6d06780220286ab2db0
Author: Guy Harris <guy@alum.mit.edu>
Date:   Tue Nov 30 15:52:45 2010 -0800

    In test programs, just as in pcap-usb-linux.c, if we have
    <linux/compiler.h> we (probably need to include it before including
    <linux/usbdevice_fs.h>, otherwise the test may fail when it shouldn't.

commit b019cc06cb4fdc01f99a36581fe7b55e2533d663
Author: Guy Harris <guy@alum.mit.edu>
Date:   Thu Nov 25 14:06:01 2010 -0800

    Check whether we have <linux/compiler.h>.

    Not all distributions have it in /usr/include; I guess the ones that
    don't have it have versions of other kernel headers that don't require
    it.

commit 0920898be2ede72baafa2a02e77ea223ecbe4f9a
Author: Guy Harris <guy@alum.mit.edu>
Date:   Thu Nov 25 13:49:16 2010 -0800

    Include <linux/compiler.h> before including <linux/usbdevice_fs.h>.

    Some versions of the Linux kernel require that.

commit 85089fea5732acc004dcc7e6aebcb0510c37f675
Author: Guy Harris <guy@alum.mit.edu>
Date:   Fri Jun 4 10:48:16 2010 -0700

    Do filtering on USB and Bluetooth capturing.

    Do the standard userland filtering on USB and Bluetooth captures, rather
    than returning "success" when the filter is installed without doing
    anything with the filter.

    Also, squelch some "dereferencing type-punned pointer will break
    strict-aliasing rules" warnings in pcap-bt-linux.c, by using memcpy
    rather than pointer-casting.