nping: Fix link issue, undefined reference to addrset_contains
libnetutil code needs addrset_contains which is provided by libnbase,
so libnbase.a must be specified after libnetutil.a

Fixes: #3012