Fix to support libressl
Support for libressl was missing causing the following build failure:
nse_openssl.cc:302:14: error: aggregate 'EVP_MD_CTX mdctx' has incomplete type and cannot be defined
  302 |   EVP_MD_CTX mdctx;
      |              ^~~~~
The above error will be present when nmap is build with libressl3.5-libcrypto libressl3.5-libssl libressl3.5-libtls libraries. It will not be present when building with libssl3 (openssl ) library.