Make data_file_record::operator< const. The lack of this might have been causing a compile error reported by Nuno GonÃ§alves:
error: passing 'const data_file_record' as 'this' argument of 'bool data_file_record::operator<(const data_file_record&)' discards qualifiers
make[4]: *** [output.o] Error 1