Fix to support libressl
Support for libressl was missing causing the following build failure:
crypt.c:71:25: error: field 'h' has incomplete type
   71 |     _libssh2_cipher_ctx h;
The above error will be present when nmap is build with libressl3.5-libcrypto libressl3.5-libssl libressl3.5-libtls libraries. It will not be present when building with libssl3 (openssl ) library.